services:
  - type: web
    name: quickbite
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm run render:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
